Issue/9
nysalad19/lamp_practice pull request #11
Opened 2021-05-05 01:28 UTC by nysalad19

購入履歴テーブルと購入明細テーブルを実行するSQLを実装しました。
developブランチへのマージをお願いします。

2021-05-05 03:20 UTC, primestyleus requested changes
@nysalad19 
エラーがあったときにfalseを返すことはできていますが、transaction については未実装のようです。実装をお願いいたします。

2021-05-06 10:42 UTC, nysalad19 commented
@primestyleus 
transactionで書いてみました。
ご確認をお願いします。

2021-05-06 11:40 UTC, primestyleus requested changes
@nysalad19 
修正ありがとうございます。あとは、問題があってrollbackした場合も、画面自体は完了画面に飛んでしまうと思います。そこだけ修正いただけますか？

2021-05-06 12:54 UTC, nysalad19 commented
@primestyleus 
コントローラー側のfinish.phpにて
カート購入の関数でfalseが返ってきた時に
カートページにリダイレクトするように処理を書いているので、
ロールバック後にfalseを返すように追記して対応をいたしました。

ご確認をお願いします。

2021-05-06 13:35 UTC, primestyleus approved these changes
@nysalad19 
OKです！修正お疲れさまでした。マージします。

2021-05-06 13:35 UTC, merged