Issue/5
nysalad19/lamp_practice pull request #6
Opened 2021-04-28 14:09 UTC by nysalad19

タグインジェクション防止のために、SQL文を利用する関数を、値をバインドする形式に変更しました。
変更したファイルは、「lamp_practice/www/model」のディレクトリの
「cart.php」「item.php」「user.php」の3つのファイルです。

developブランチへのマージをお願いします。

2021-04-28 14:31 UTC, primestyleus requested changes
@nysalad19 
SQLインジェクション対策はOKです！ただ、1箇所別の部分で修正が必要なので、ご確認をお願いします。

2021-04-28 14:31 UTC, primestyleus commented on www/model/functions.php
> +  return substr(base_convert(hash('sha256', uni_id()), 16, 36), 0, $length);
コーディングのときに間違って書き換わってしまったのかもしれません。
「uni_id」ではなく「uniqid」が正しいです。

2021-04-28 23:33 UTC, nysalad19 commented on www/model/functions.php
> +  return substr(base_convert(hash('sha256', uni_id()), 16, 36), 0, $length);
@primestyleus 
ご確認ありがとうございます。
間違えた上書きをしてしまい申し訳ありません。
www/model/functions.phpの該当部分を「uniqid」に修正し、issue/5ブランチにプッシュしました。
ご確認をよろしくお願いいたします。

2021-04-29 00:01 UTC, primestyleus approved these changes
@nysalad19

2021-04-29 00:02 UTC, primestyleus commented on www/model/functions.php
> +  return substr(base_convert(hash('sha256', uni_id()), 16, 36), 0, $length);
@nysalad19  修正お疲れさまでした。マージします。

2021-04-29 00:02 UTC, merged